---
title: "mombourquette_Assignment6"
author: "Janine Mombourquette"
date: "2025-11-01"
output:
  pdf_document: default
  html_document: default
---

# Cooperative nest defense by European Starlings (*Sturnus vulgaris*) during a predatory threat
#### Paper by Elizabeth A. Lewis and Colleen A. Barber
##### Data and code for this assignment can be accessed through GitHub: https://github.com/JanineMombourquette/DSassignment6_Janine

### Introduction
Cooperative nest defense is when birds (usually those of the same species) work together to defend a nest from a threat (Beletsky and Orians, 1989). Some common behaviours involved in cooperative nest defense include alarm calling and mobbing (da Cunha et al., 2017a). This type of activity is very risky to participate in, as these individuals are making themselves known to the predator (Lewis & Barber, 2023). Typically, it is male birds who take part in these activities (da Cunha et al., 2017b). One potential theory for why this occurs is related to the reproductive strategies of these animals (Brown, 1987). In many species, male birds often mate with several females and have offspring in multiple nests (Gibbs et al., 1990). Since these birds want to protect all of their offspring, it is thought that the males would work together to protect the nests in the population just in case they had offspring in some of them (Lewis & Barber, 2023). The study species for this paper was the European starling. These are a social, cavity nesting passerine species (Lewis & Barber, 2023). There is a lack of knowledge on starlings' investment in nest defense (Lewis & Barber, 2023). An important characteristic of starlings is that due to their mixed reproductive strategies, both males and females can have offspring in multiple nests (Lewis & Barber, 2023). Thus, females may be motivated to participate in cooperative nest defense for this reason (Lewis & Barber, 2023). The objectives of this paper were to determine if European starlings partake in cooperative nest defense, and if so, do both males and females participate in this behaviour (Lewis & Barber, 2023).

### Methods
This study took place during May-July 2015, during the European starling breeding season (Lewis & Barber, 2023). To identify the birds during the study, they were given coloured bands which allowed researchers to ID and sex birds at a distance. This study used 16 nest boxes on the Saint Mary's University campus. They exposed the nest boxes to two trials, an experimental trial (where a taxidermy American red squirrel was placed on the nest box) and a control trial (where a rock of similar colour and dimensions to the squirrel were placed on the nest box). Trials lasted for 3 minutes and began when an adult arrived at the box. During this time, observations were recorded, including the adults that were present and the defense behaviours they displayed. Individual defense behaviours were counted once per trial and given a score. The potential behaviours and scores were as follows: no reaction (0), alarm calls or chips (1), fly-bys (2), dives (3), hits (4). These were then combined to get an aggregate score for each trial type at each nest box ranging from 0 to 10. Researchers used a Wilcoxon matched pairs signed-rank test to analyze the total number of starlings that flew to the nest box. They used this same test to analyze the aggregate defense scores for the two trials. For analyzing the number of non-parent starlings who responded to experimental and control trials, a Fisher's Exact test was performed. Fisher's Exact tests were also used to analyze parental response between the trial types (Lewis & Barber, 2023). 

### Results and conclusions
Researchers found that starlings (both parents at the box and other unrelated individuals) flew to nest boxes significantly more during experimental trials compared to control trials (Wilcoxon *W* = 45, *N* = 16, *p* = 0.004) (Lewis & Barber, 2023). The highest number of responding birds in a trial was 7 individuals (one parent and seven other starlings) during an experimental trial. Of all of the unrelated starlings that defended other nest boxes, 11 were identified as male and 3 were identified as female (Lewis & Barber, 2023). 

It was found that the aggregate scores for the experimental trial (the American red squirrel) were significantly higher than the responses to the control trial (the rock) (*W* = 120, *N* = 16, *p* < 0.0001), as shown in Figure 1 (Lewis & Barber, 2023). The highest aggregate score was 10, which was observed during an experimental trial. The most common defense tactic was alarm calls/chips, which occurred in all experimental trials (Lewis & Barber, 2023). 

```{r, echo=FALSE}
library(ggplot2)
birds <- read.csv("birds_scores.csv")
ggplot(birds, aes(x = Trial, y = aggregate_score)) +
  geom_boxplot() +
  labs(x = "Trial",
       y = "Aggregate Score") +
  theme_classic() +
  theme(legend.position = "none")
```
Figure 1. Aggregate scores of European starling nest defense behaviours when exposed to control (n = 16) and experimental (n = 16) trials

Researchers were able to answer the two objectives of this article. They found that cooperative nest defense does occur in European starlings and that both females and males participated (Lewis & Barber, 2023). The authors propose that a next step for this work could be doing DNA analysis to study the genetic relationships among the adult birds and the nestlings they defended to determine if cooperative nest defense is influenced by this factor (Lewis & Barber, 2023).

### References
Beletsky, L. D., and G. H. Orians. 1989. Familiar neighbors enhance breeding success in birds. *Proceedings of the National Academy of Sciences* 86(20):7933-7936. https://doi.org/10.1073/pnas.86.20.7933

Brown, J. L. 1987. Helping communal breeding in birds: ecology and evolution. *Princeton University Press*, Princeton, New Jersey, USA. https://doi.org/10.1515/9781400858569

da Cunha, F. C. R., J. C. R. Fontenelle, and M. Griesser. 2017a. Predation risk drives the expression of mobbing across bird species. *Behavioral Ecology* 28(6):1517-1523. https://doi.org/10.1093/beheco/arx111  

da Cunha, F. C. R., J. C. R. Fontenelle, and M. Griesser. 2017b. The presence of conspecific females influences male-mobbing behavior. *Behavioral Ecology and Sociobiology* 71:52. https://doi.org/10.1007/s00265-017-2267-7

Gibbs, H. L., P. J. Weatherhead, P. T. Boag, B. N. White, L. M. Tabak, and D. J. Hoysak. 1990. Realized reproductive success of polygynous red-winged blackbirds revealed by DNA markers. *Science* 250(4986):1394-1397. https://doi.org/10.1126/science.250.4986.1394

Lewis, E., & Barber, C. 2023. Cooperative nest defense by European Starlings (*Sturnus vulgaris*) during a predatory threat. *Journal of Field Ornithology* 94(3), art13. https://doi.org/10.5751/JFO-00326-940313